### ISSUE TITLE
Algorithm robustness

### ISSUE THREAD

**Issue by htaoruan** [QinjieXiao/EyelashNet#6]
Hello, when entering a photo that contains eyebrows and hair, the eyebrows and hair will also be matting. If only the area of the eyes that includes eyelashes is entered, it will result in the inability to matting. Do you have any good suggestions for this?
![image](https://github.com/user-attachments/assets/e23f1a61-50bc-41a2-a47d-9125b61e47e6)

**Comment by summertight** [comment]
@htaoruan How did you solve this issue?
